@JobTrackerApi_HostAddress = http://localhost:5195
@AccessToken = eyJhbGciOiJIUzI1NiIsImtpZCI6ImdLd3BReVk3cE5iOC8wejQiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2Z4aGNwb2l1bW5tb3ZkZHNoZm11LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiIxYjU1NDdmZS03YmNlLTQxNWYtODcwMC02OTZmYzZkMGU0ODYiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzQ5MDU4MzM4LCJpYXQiOjE3NDkwNTQ3MzgsImVtYWlsIjoiam1lbGdhcjQyMEBnbWFpbC5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7ImVtYWlsX3ZlcmlmaWVkIjp0cnVlfSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJwYXNzd29yZCIsInRpbWVzdGFtcCI6MTc0OTAxMjMxOX1dLCJzZXNzaW9uX2lkIjoiNzdiZTRiZWItMGY0MC00NDY1LWE3MjMtNmQ2YTY2MDA4ZjUyIiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.BJoouJTztCZo2XyqxafKD-XsChl5nPnrwDZx8F-V0E

GET {{JobTrackerApi_HostAddress}}/api/jobapplication
Accept: application/json
Authorization: Bearer {{AccessToken}}

###
